name: Generate README

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 3 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: go install github.com/muesli/markscribe@latest

      - run: markscribe README.template.md > README.md

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "chore: update README" || echo "No changes to commit"
          git push
