name: Update README with Wakatime Stats

on:
  push:
    branches: [ main ]
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install markscribe
      run: go install github.com/taciturnaxolotl/markscribe@latest
    
    - name: Generate Wakatime content
      id: wakatime
      run: |
        WAKATIME_CONTENT=$(markscribe .github/templates/wakatime-languages.tpl)
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$WAKATIME_CONTENT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        WAKATIME_URL: "https://hackatime.hackclub.com/api/hackatime/v1"
    
    - name: Update README
      run: |
        python3 << 'EOF'
        import re
        
        # Read the current README
        with open('README.md', 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Replace the content between markers
        wakatime_content = '''${{ steps.wakatime.outputs.content }}'''
        
        pattern = r'<!-- WAKATIME-LANGUAGES:START -->.*?<!-- WAKATIME-LANGUAGES:END -->'
        replacement = f'<!-- WAKATIME-LANGUAGES:START -->\n{wakatime_content}\n<!-- WAKATIME-LANGUAGES:END -->'
        
        new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)
        
        # Write back to README
        with open('README.md', 'w', encoding='utf-8') as f:
            f.write(new_content)
        EOF
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Wakatime language stats"
          git push
        fi